AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an RDS MySQL instance

Parameters:
  DBName:
    Type: String
    Description: The database name
  DBUser:
    Type: String
    Description: The database admin account username
  DBPassword:
    Type: String
    Description: The database admin account password
Resources:
  MySQLDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      Engine: MySQL
      DBInstanceClass: db.t4g.micro
      StorageType: gp2
      PubliclyAccessible: true
      AllocatedStorage: "20"
      DBInstanceIdentifier: !Join ["-", [ "nequidatabase", !Ref "AWS::Region" ]]
      AvailabilityZone: !Select [1, !GetAZs ""]
