spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3310/clase9test}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true